### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by beckermr**
This PR rebuilds the feedstock. 

Closes #15 
Closes #16

### CODE REVIEW

**Comment by beckermr** [comment]
This PR appears to be blocked a test failure.

**Comment by duncanwp** [comment]
I'll take a look, thanks

**Comment by duncanwp** [comment]
I've bumped the version but now the build is failing for some other reason, it looks like a condo-forge issue but I'm not sure...

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Now that the switch is done we probably need to rerender.

**Comment by beckermr** [comment]
raised here: https://github.com/conda-forge/dask-feedstock/issues/60

**Comment by duncanwp** [comment]
Great, thanks. That is odd...

**Comment by beckermr** [comment]
Post move to the new compilers we don't need 1000 build numbers anymore.

**Comment by beckermr** [comment]
@duncanwp There appears to now be a version conflict on the windows build. Can you look into this? I def changed some of the version constraints in the recipe, so someone who knows the package looking through them would be great.

**Comment by duncanwp** [comment]
OK, the pyhdf feedstock has dropped [windows support](https://github.com/conda-forge/pyhdf-feedstock/issues/16), I'm trying to figure out why

**Comment by duncanwp** [comment]
@conda-forge-admin, please rerender

**Comment by duncanwp** [comment]
@conda-forge-admin, please update circle

**Pull request merged**
