### PR TITLE
Re-render with `conda-smithy` version `1.0.0`

### PR DESCRIPTION
**Pull request by jakirkham**
This is a re-rendering generated with `conda-smithy` version `1.0.0`.

It provides a fix so that the Travis CI build will be skipped in this feedstock as this does not build on OS X. If this changes, update the `skip` conditions in the recipe and re-render.

Also it starts using [`conda-forge-build-setup`]( https://github.com/conda-forge/conda-forge-build-setup-feedstock ) to handle standard CI setup like what version of `conda-build` is used. This should allow us to more quickly get out in front of build issues that generally affect feedstocks.

Letting you know @pelson that I'm taking this for a spin.

### CODE REVIEW

**Comment by jakirkham** [comment]
This is suffering from the same `icu` issues that we have seen with `qt` elsewhere in the stack.

**Comment by jakirkham** [comment]
In other words, this does not cause any problem. It merely reveals and existing problem that affects this package.

**Comment by pelson** [comment]
Is this caused by qt again?

**Comment by jakirkham** [comment]
Yes. Though I guess the story is more complicated ( https://github.com/conda-forge/matplotlib-feedstock/pull/42 ).

**Comment by jakirkham** [comment]
FWIW this PR isn't causing the failure. It is merely exposing a failure that this feedstock is already suffering from.

**Pull request merged**
